name: Publish NuGet Package

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      PACKAGE_NAME: DSK.Common.DependencyInjection
      PACKAGE_VERSION: 1.0.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Debug: list files in the root directory to confirm solution file exists.
      - name: List root directory files
        run: ls -la

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Adjust this if you need to target a different .NET version

      # Restore dependencies from the correct solution file
      - name: Restore dependencies
        run: dotnet restore DSK.Common.DependencyInjection.sln

      # Build the solution using the correct solution file
      - name: Build solution
        run: dotnet build DSK.Common.DependencyInjection.sln --configuration Release

      # Pack the project using the correct project file path
      - name: Pack the project
        run: dotnet pack src/DSK.Common.DependencyInjection/DSK.Common.DependencyInjection.csproj --configuration Release --no-build -o ./nupkgs /p:PackageVersion=${{ env.PACKAGE_VERSION }}

      # Debug: list generated packages to verify the .nupkg file exists
      - name: List generated packages
        run: ls -la ./nupkgs

      # Push the NuGet package to GitHub Packages
      - name: Push NuGet package to GitHub Packages
        run: |
          dotnet nuget push ./nupkgs/*.nupkg \
            --source "https://nuget.pkg.github.com/Deskstones/index.json" \
            --api-key "$NUGET_API_KEY" -v detailed
