name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      PACKAGE_NAME: DSK.Common.DependencyInjection
      PACKAGE_VERSION: 1.0.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ env.PACKAGE_NAME }}.sln

      - name: Build solution
        run: dotnet build ${{ env.PACKAGE_NAME }}.sln --configuration Release

      - name: Pack the project
        run: dotnet pack Src/${{ env.PACKAGE_NAME }}/${{ env.PACKAGE_NAME }}.csproj --configuration Release --no-build -o ./nupkgs /p:PackageVersion=${{ env.PACKAGE_VERSION }}

      - name: Push NuGet package to GitHub Packages
        run: |
          dotnet nuget push ./nupkgs/*.nupkg \
            --source "https://nuget.pkg.github.com/Deskstones/index.json" \
            --api-key "$NUGET_API_KEY"
